### ISSUE TITLE
[isIterable] ts报错 类型“unique symbol”不能作为索引类型使用

### ISSUE THREAD

**Issue by c0dedance** [wtklbm/curong#4]
(property) SymbolConstructor.iterator: typeof Symbol.iterator
A method that returns the default iterator for an object. Called by the semantics of the for-of statement.
类型“unique symbol”不能作为索引类型使用。
`export const isObject = (value: unknown): value is Record<any, any> =>
  value !== null && typeof value === 'object';
export const isFunction = (value: unknown): value is Function => typeof value === 'function';
export const isIterable = (value: unknown): value is Iterable<any> => isObject(value) && (isFunction(value[Symbol.iterator]) || isFunction(value[Symbol.asyncIterator]));
`
![image](https://user-images.githubusercontent.com/38075730/189724139-90876e1a-d434-4958-9672-34e301bbe763.png)

**Comment by wtklbm** [comment]
```js
// 修改 Record<any, any>
export const isObject = (
    value: unknown
): value is Record<string | number | symbol, any> =>
    value !== null && typeof value === 'object';

export const isFunction = (value: unknown): value is Function =>
    typeof value === 'function';

export const isIterable = (value: unknown): value is Iterable<any> =>
    isObject(value) &&
    (isFunction(value[Symbol.iterator]) ||
        isFunction(value[Symbol.asyncIterator]));

const s = new Set([1, 2, 3]);
console.log(isIterable(s));
```

**Comment by c0dedance** [comment]
it is so cool!

> ```js
> // 修改 Record<any, any>
> export const isObject = (
>     value: unknown
> ): value is Record<string | number | symbol, any> =>
>     value !== null && typeof value === 'object';
> 
> export const isFunction = (value: unknown): value is Function =>
>     typeof value === 'function';
> 
> export const isIterable = (value: unknown): value is Iterable<any> =>
>     isObject(value) &&
>     (isFunction(value[Symbol.iterator]) ||
>         isFunction(value[Symbol.asyncIterator]));
> 
> const s = new Set([1, 2, 3]);
> console.log(isIterable(s));
> ```
